### ISSUE TITLE
Script file not found

### ISSUE THREAD

**Issue by sealr00t** [k6io/intellij-plugin#12]
Hi.

I’m having some issue when using k6 plugin with WebStorm IDE.

I’m able to add a new run configuration and execute it successfully - but I get an error on the run conf window saying “Error: Script file does not exist: {path to script}” (check attached image), which forces me to do some extra clicks when running it.

Also when activating the “Show thresholds as tests” on the run config window break the config (check attached image).

I’m wondering am I doing something wrong here or this issue is out of my control.

![Screenshot at Feb 01 23-06-09](https://user-images.githubusercontent.com/44849075/152176733-cc58ae12-551e-4e4e-bcc3-d21c5f2d5578.png)

**Comment by mbolotov** [comment]
Hi @sealr00t!
The `k6 Script path` value is expected to be an absolute path. Relative path cause the validation error as you see. 
The question here is how you get this relative path? Does it get inserted automatically when you create a run configuration?
Or you change it manually later?

**Comment by sealr00t** [comment]
Hi @mbolotov!

Thanks for replying. I think it would be great if we could be able to add support for relative paths as I could share these run configs with other people without worrying about the absolute path of my script files.

That was manually added by me.  

Thanks

**Comment by mbolotov** [comment]
Okay, I will do this under the new repository:
https://github.com/mbolotov/k6-intellij-plugin/issues/2
