### ISSUE TITLE
k6 Run Configuration feature

### ISSUE THREAD

**Issue by mbolotov** [k6io/intellij-plugin#2]
Please introduce Run Configuration feature for k6 test script execution. 
This feature allows running k6 scripts in common way as other tools are executed within IntelliJ platform.
Beside that, a run configuration can be configured to build the project automatically before execution and so allowing to run a TypeScript k6 test in a one click.
![image](https://user-images.githubusercontent.com/19785715/111151524-9d954880-85a0-11eb-8c69-855570e87374.png)

**Comment by ppcano** [comment]
Given how [Thresholds](https://k6.io/docs/using-k6/thresholds) works:

> In the above case, the criteria for both thresholds were met. The whole load test is considered to be a pass, which means that k6 will exit with exit code zero.
> If any of the thresholds had failed, the little green checkmark ✓ next to the threshold name (http_req_failed, http_req_duration) would have been a red cross ✗ instead, and k6 would have generated a non-zero exit code.


The run configuration should read the k6 CLI exit code to mark the test as Pass or Failure.
