### ISSUE TITLE
Cannot run program "k6" (in directory "/xxx"): error=2, No such file or directory

### ISSUE THREAD

**Issue by FrankLoud** [k6io/intellij-plugin#5]
k6 0.1.0
idea 2020.3

Cannot run program "k6" (in directory "/xxx"): error=2, No such file or directory
![image](https://user-images.githubusercontent.com/17379803/114497034-cb2ee980-9c53-11eb-88ec-9902ae5db427.png)
![image](https://user-images.githubusercontent.com/17379803/114497071-e00b7d00-9c53-11eb-98bc-a98a8c7cbfe4.png)

**Comment by mbolotov** [comment]
Hi @FrankLoud!
do you have k6 executable set in your OS path? can you run `k6` from command line successfully?

**Comment by FrankLoud** [comment]
Hi @mbolotov yes. I install k6 global.

**Comment by mbolotov** [comment]
that's strange.
is it possible to show how the final command looks like? You may reach me directly on slack if this will be acceptable from the security point of view: https://intellij-cypress.slack.com/archives/DTZ00KH6D
Or you could just look by yourself closely to the final run command - this is the command the log shows at the first line:
![image](https://user-images.githubusercontent.com/19785715/114696712-a5721500-9d25-11eb-8824-0348f2218dff.png)
does it have something wrong? can you this command successfully via a terminal?

**Comment by mbolotov** [comment]
Hey, @FrankLoud!
Are you still experiencing the problem?

**Comment by RobinCheptileh** [comment]
Hi @mbolotov
I'm getting the same error. I have installed k6 globally and I can run the same command successfully on terminal.

K6: `k6 v0.31.1 ((devel), go1.16.2, darwin/amd64)`
Idea: `IntelliJ IDEA 2021.1 Build #IU-211.6693.111, built on April 6, 2021`

**Comment by mbolotov** [comment]
Hi Robin!
Could you please check if the problem has been fixed in this plugin bundle? I just have no access to a Mac OS to verify. 
[k6-0.2.1-SNAPSHOT.zip](https://github.com/k6io/intellij-plugin/files/6398803/k6-0.2.1-SNAPSHOT.zip)
You can install the bundle as following:
![image](https://user-images.githubusercontent.com/19785715/116556684-68517980-a906-11eb-9865-10bd3b6ef6b3.png)

**Comment by sandy999** [comment]
I was running in similar issue. Installing the snapshot fixed it.

**Comment by mbolotov** [comment]
Thanks, @sandy999!
Then I will release this fix soon
